<div class="page-title">
    <h1><?php echo $this->__('Two Factor Authentication') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="twofactorauth-form">
    <input type="hidden" name="secret" value="<?php echo $this->getSecret(); ?>" />

    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Settings') ?></h2>
        <ul class="form-list">
            <li class="control">
                <label for="subscription"><?php echo $this->__('Enable') ?></label>
                <select name="enabled" id="twofactorauth-enabled">
                    <option value="0"><?php echo $this->__('No'); ?></option>
                    <option value="1" <?php if ($this->isEnabled()) { ?>selected="selected"<?php } ?>><?php echo $this->__('Yes'); ?></option>
                </select>
            </li>
        </ul>
    </div>
    <div class="fieldset"  id="twofactorauth-configure">
        <h2 class="legend"><?php echo $this->__('Configure') ?></h2>

        <p><?php echo $this->__('To configure a 2fa app, simply scan the QR code below and enter the code below.'); ?></p>

        <ul class="form-list">
            <li class="control">
                <label for="subscription"><?php echo $this->__('Configure') ?></label>
                <img src="<?php echo $this->getQrCodeImageUrl(); ?>" />
            </li>
            <li class="control">
                <label for="subscription"><?php echo $this->__('Verify Code') ?></label>
                <input type="text" name="code" value="" />
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>