<?php /** @var $this Mage_Adminhtml_Block_Template */
/** @var $element MageHackDay_TwoFactorAuth_Block_Adminhtml_System_Account_Form_Questions */
$element = $this->getElement();
$rowCount = $element->getData('row_count');
if ( ! $rowCount) $rowCount = 5;
$questions = $element->getData('value');
?>
<div id="<?php echo $element->getHtmlId() ?>">
    <div class="grid">
        <table cellspacing="0" class="data border" style="margin: 5px 0;">
            <colgroup>
                <col width="1"/>
                <col width="400"/>
                <col width="400"/>
            </colgroup>
            <thead>
                <tr class="headings">
                    <th><?php echo Mage::helper('twofactorauth')->__('#') ?></th>
                    <th><?php echo Mage::helper('twofactorauth')->__('Question') ?></th>
                    <th><?php echo Mage::helper('twofactorauth')->__('Answer') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php for ($i = 0; $i < $rowCount; $i++):  ?>
                <tr>
                    <td><?php echo $i+1 ?></td>
                <?php foreach (array('question', 'answer') as $field): ?>
                    <?php $name = $element->getFieldName($i, $field) ?>
                    <?php $value = isset($questions[$i][$field]) ? $questions[$i][$field] : '' ?>
                    <td>
                        <input type="text" name="<?php echo $name ?>" value="<?php echo $value ?>" class="input-text" style="width: 400px" maxlength="100" />
                    </td>
                <?php endforeach; ?>
                </tr>
              <?php endfor; ?>
            </tbody>
        </table>
        <p class="nm"><small><?php echo Mage::helper('twofactorauth')->__('Maximum length for the questions and answers is 100 symbols.') ?></small></p>
    </div>
</div>